In [2]:
import numpy as np
#creating a numpy array
numbers=np.array([3,10,7,2,15,8,21,14])

print("Array:",numbers)
print("Type:",type(numbers))
print("data type",numbers.dtype)
print("Shape:",numbers.shape)
print("Length",len(numbers))

Array: [ 3 10  7  2 15  8 21 14]
Type: <class 'numpy.ndarray'>
data type int64
Shape: (8,)
Length 8


In [3]:
#array operations
numbers=np.array([3,10,7,2,15,8,21,14])
print("Original",numbers)
print("ADD 10:",numbers+10)
print("Multiply by 2",numbers*2)
print("Square",numbers**2)
print("Greater than 10:",numbers>10)
print("Sum:",np.sum(numbers))
print("Mean:",np.mean(numbers))
print("Max:",np.max(numbers))
print("Min:",np.min(numbers))
print("Sorted:",np.sort(numbers))
print("Greater than 10:",numbers[numbers>10])
print("descending Sorted:",np.sort(numbers)[::-1])

Original [ 3 10  7  2 15  8 21 14]
ADD 10: [13 20 17 12 25 18 31 24]
Multiply by 2 [ 6 20 14  4 30 16 42 28]
Square [  9 100  49   4 225  64 441 196]
Greater than 10: [False False False False  True False  True  True]
Sum: 80
Mean: 10.0
Max: 21
Min: 2
Sorted: [ 2  3  7  8 10 14 15 21]
Greater than 10: [15 21 14]
descending Sorted: [21 15 14 10  8  7  3  2]


In [4]:
#2D array
marks_2d=np.array([
    [85,72,91],
    [65,78,88],
    [90,55,70]
])
print("2D array:\n",marks_2d)
print("Shape",marks_2d.shape)
print("First row:",marks_2d[0])
print("First Column:",marks_2d[:,0])
print("Element at row 1 ,col 2:",marks_2d[0][1])
print("Element at row 1 ,col 2:",marks_2d[0,1])
print("Column means:",np.mean(marks_2d,axis=0))
print("Row means:",np.mean(marks_2d,axis=1))

2D array:
 [[85 72 91]
 [65 78 88]
 [90 55 70]]
Shape (3, 3)
First row: [85 72 91]
First Column: [85 65 90]
Element at row 1 ,col 2: 72
Element at row 1 ,col 2: 72
Column means: [80.         68.33333333 83.        ]
Row means: [82.66666667 77.         71.66666667]


In [5]:
import pandas as pd 

#Creating a series
marks=pd.Series([85,72,91,65,78])
print("Series :\n",marks)
print("\n Type:",type(marks))
print("Values",marks.values)
print("Index:",marks.index)


Series :
 0    85
1    72
2    91
3    65
4    78
dtype: int64

 Type: <class 'pandas.core.series.Series'>
Values [85 72 91 65 78]
Index: RangeIndex(start=0, stop=5, step=1)


In [6]:
#Series with the custom index
marks=pd.Series(
    [85,72,91,65,78],
    index=["Naveen","Akash","Devika","Shreya","Nithin"])
print("Series with name:")
print(marks)
print("\nNaveen's marks:", marks["Naveen"])
print("Marks above 75:",marks[marks>75])

Series with name:
Naveen    85
Akash     72
Devika    91
Shreya    65
Nithin    78
dtype: int64

Naveen's marks: 85
Marks above 75: Naveen    85
Devika    91
Nithin    78
dtype: int64


In [7]:
#creating a DataFrame
data={
    "Name":["Navven","Akash","Devika","Shreya","Nithin"],
    "Age":[20,21,19,22,20],
    "Marks":[85,72,91,65,78],
    "City":["Bengaluru","Mysore","Bengaluru","Hubli","Mangaluru"]
}
df=pd.DataFrame(data)
print(df)

     Name  Age  Marks       City
0  Navven   20     85  Bengaluru
1   Akash   21     72     Mysore
2  Devika   19     91  Bengaluru
3  Shreya   22     65      Hubli
4  Nithin   20     78  Mangaluru


In [8]:
#Exploring the DataFrame
print("Shape:",df.shape)
print("\n columns:",df.columns.tolist())
print("\nData types:\n",df.dtypes)
print("\nFrist 3 rows:\n",df.head(3))
print("\nLast 2 rows:\n",df.tail(2))
print("\nBasic statistics:\n",df.describe())
print("\nInfo:")
df.info()

Shape: (5, 4)

 columns: ['Name', 'Age', 'Marks', 'City']

Data types:
 Name     object
Age       int64
Marks     int64
City     object
dtype: object

Frist 3 rows:
      Name  Age  Marks       City
0  Navven   20     85  Bengaluru
1   Akash   21     72     Mysore
2  Devika   19     91  Bengaluru

Last 2 rows:
      Name  Age  Marks       City
3  Shreya   22     65      Hubli
4  Nithin   20     78  Mangaluru

Basic statistics:
              Age      Marks
count   5.000000   5.000000
mean   20.400000  78.200000
std     1.140175  10.281051
min    19.000000  65.000000
25%    20.000000  72.000000
50%    20.000000  78.000000
75%    21.000000  85.000000
max    22.000000  91.000000

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    5 non-null      object
 1   Age     5 non-null      int64 
 2   Marks   5 non-null      int64 
 3   City    5 non-null      

In [9]:
data={
"product":["pen","notebook","pencil","marker","eraser"],
 "price":[20,50,5,25,10],
 "qty":[10,5,30,8,15]}
df=pd.DataFrame(data)
print(df)
 

    product  price  qty
0       pen     20   10
1  notebook     50    5
2    pencil      5   30
3    marker     25    8
4    eraser     10   15


In [10]:
print("Shape:",df.shape)
print("\n columns:",df.columns.tolist())
print("\nData types:\n",df.dtypes)
print("\nBasic statistics:\n",df.describe())

Shape: (5, 3)

 columns: ['product', 'price', 'qty']

Data types:
 product    object
price       int64
qty         int64
dtype: object

Basic statistics:
            price        qty
count   5.000000   5.000000
mean   22.000000  13.600000
std    17.535678   9.864076
min     5.000000   5.000000
25%    10.000000   8.000000
50%    20.000000  10.000000
75%    25.000000  15.000000
max    50.000000  30.000000


In [11]:
#First create a sample csv file 
import pandas as pd 
data=data={
    "Name":["Navven","Akash","Devika","Shreya","Nithin"],
    "Age":[20,21,19,22,20],
    "Marks":[85,72,91,65,78],
    "City":["Bengaluru","Mysore","Bengaluru","Hubli","Mangaluru"]
}
df=pd.DataFrame(data)
df.to_csv("students.csv",index=False)
print("students.csv Created.")

students.csv Created.


In [12]:
#Load Csv using pandas
df=pd.read_csv("students.csv")
print("Loaded Csv:")
print(df)
print("\nshape:",df.shape)

Loaded Csv:
     Name  Age  Marks       City
0  Navven   20     85  Bengaluru
1   Akash   21     72     Mysore
2  Devika   19     91  Bengaluru
3  Shreya   22     65      Hubli
4  Nithin   20     78  Mangaluru

shape: (5, 4)


In [13]:
#accessing columns
print("Names column:")
print(df["Name"])

print("\nmarks column:")
print(df["Marks"])
print("\nMultipe columns:")
print(df[["Name","Marks"]])
#Accessing rows
print("\nFirst row(iloc):")
print(df.iloc[0])

print("\nRows 1 to 3:")
print(df.iloc[0:3])

Names column:
0    Navven
1     Akash
2    Devika
3    Shreya
4    Nithin
Name: Name, dtype: object

marks column:
0    85
1    72
2    91
3    65
4    78
Name: Marks, dtype: int64

Multipe columns:
     Name  Marks
0  Navven     85
1   Akash     72
2  Devika     91
3  Shreya     65
4  Nithin     78

First row(iloc):
Name        Navven
Age             20
Marks           85
City     Bengaluru
Name: 0, dtype: object

Rows 1 to 3:
     Name  Age  Marks       City
0  Navven   20     85  Bengaluru
1   Akash   21     72     Mysore
2  Devika   19     91  Bengaluru


In [14]:
#Adding new columns
df["Result"]=df["Marks"].apply(lambda x: "Pass" if x>=60 else "Fail")
df["grade"]=df["Marks"].apply(lambda x: "A" if x>=80 else "B" if x>= 60 else "C")
print("DataFrame with Result and Grade:")
print(df)

DataFrame with Result and Grade:
     Name  Age  Marks       City Result grade
0  Navven   20     85  Bengaluru   Pass     A
1   Akash   21     72     Mysore   Pass     B
2  Devika   19     91  Bengaluru   Pass     A
3  Shreya   22     65      Hubli   Pass     B
4  Nithin   20     78  Mangaluru   Pass     B


In [15]:
df["age_group"]=df["Age"].apply(lambda x: "Senior" if x>=21 else "junior")
print("DataFrame with Age Group")
print(df)

DataFrame with Age Group
     Name  Age  Marks       City Result grade age_group
0  Navven   20     85  Bengaluru   Pass     A    junior
1   Akash   21     72     Mysore   Pass     B    Senior
2  Devika   19     91  Bengaluru   Pass     A    junior
3  Shreya   22     65      Hubli   Pass     B    Senior
4  Nithin   20     78  Mangaluru   Pass     B    junior


In [16]:
#Filtering with Pandas
df=pd.read_csv("Students.csv")

# Filter students who are passed

passed=df[df["Marks"]>=60]
print("Passed students:")
print(passed)

#Filtering students from Bemgaluru
bengaluru=df[df["City"]=="Bengaluru"]
print("\nstudents froooom Bengaluru are:")
print(bengaluru)

#Multipleconditions
passed_bengaluru=df[(df["Marks"]>=60) & (df["City"]=="Bengaluru")]
print("\nPassed students from bengaluru are:")
print(passed_bengaluru)

Passed students:
     Name  Age  Marks       City
0  Navven   20     85  Bengaluru
1   Akash   21     72     Mysore
2  Devika   19     91  Bengaluru
3  Shreya   22     65      Hubli
4  Nithin   20     78  Mangaluru

students froooom Bengaluru are:
     Name  Age  Marks       City
0  Navven   20     85  Bengaluru
2  Devika   19     91  Bengaluru

Passed students from bengaluru are:
     Name  Age  Marks       City
0  Navven   20     85  Bengaluru
2  Devika   19     91  Bengaluru


In [17]:
df.iloc[0,0]="Naveen"

In [18]:
print(passed_bengaluru)

     Name  Age  Marks       City
0  Navven   20     85  Bengaluru
2  Devika   19     91  Bengaluru


In [19]:
#Sorting with Pandas
#Sorting by Marks descending
sorted_marks=df.sort_values("Marks",ascending=False)
print("Sorted ny marks(high to low):")
print(sorted_marks)

#sort by Name Alphabetically
sorted_name=df.sort_values("Name",ascending=True)
print(sorted_name)


#sort By multiple columns
sorted_mult=df.sort_values(["City","Marks"],ascending=[True,False])
print("\nSorted by City then Marks:")
print(sorted_mult)

Sorted ny marks(high to low):
     Name  Age  Marks       City
2  Devika   19     91  Bengaluru
0  Naveen   20     85  Bengaluru
4  Nithin   20     78  Mangaluru
1   Akash   21     72     Mysore
3  Shreya   22     65      Hubli
     Name  Age  Marks       City
1   Akash   21     72     Mysore
2  Devika   19     91  Bengaluru
0  Naveen   20     85  Bengaluru
4  Nithin   20     78  Mangaluru
3  Shreya   22     65      Hubli

Sorted by City then Marks:
     Name  Age  Marks       City
2  Devika   19     91  Bengaluru
0  Naveen   20     85  Bengaluru
3  Shreya   22     65      Hubli
4  Nithin   20     78  Mangaluru
1   Akash   21     72     Mysore


In [20]:
score=df[df["Marks"]<70]
print(score)
    

     Name  Age  Marks   City
3  Shreya   22     65  Hubli


In [21]:
sorted_marks=df.sort_values("Marks",ascending=True)
print(score[["Name","Marks"]])

     Name  Marks
3  Shreya     65


In [22]:
import numpy as np
scores = np.array([82, 67, 91, 74, 88, 95, 69, 77, 84, 72])
print("Sum:", np.sum(scores))
print("Mean:", np.mean(scores))
print("Max:", np.max(scores))
print("Min:", np.min(scores))
above_75 = scores[scores > 75]
print("Scores above 75:", above_75)
desc_sorted = np.sort(scores)[::-1]
print("Descending order:", desc_sorted)
marks_2d = np.array([
    [85, 78, 92],
    [88, 74, 81],
    [90, 89, 84]
])
print("\n2D Array:\n", marks_2d)
col_means = np.mean(marks_2d, axis=0)
print("Subject averages:", col_means)
row_means = np.mean(marks_2d, axis=1)
print("Student averages:", row_means)

Sum: 799
Mean: 79.9
Max: 95
Min: 67
Scores above 75: [82 91 88 95 77 84]
Descending order: [95 91 88 84 82 77 74 72 69 67]

2D Array:
 [[85 78 92]
 [88 74 81]
 [90 89 84]]
Subject averages: [87.66666667 80.33333333 85.66666667]
Student averages: [85.         81.         87.66666667]


In [23]:
import pandas as pd 
data={
    "Name":["Naeven","Akash","Devika","Shreya","Nithin","vidarth","vinay","Nandan"],
    "Age":[20,21,19,22,20,21,21,22],
    "Marks":[85,72,91,65,78,89,92,96],
    "City":["Bengaluru","Mysore","Bengaluru","Hubli","Mangaluru","Dharwada","Shivamogga","Shivamogga"]
    
}
df=pd.DataFrame(data)
print("Shape:",df.shape)
print("\nData types:\n",df.dtypes)
print("\nBasic statistics:\n",df.describe())
print("\nINFO")
df.info()
df["Result"]=df["Marks"].apply(lambda x: "Pass" if x>=60 else "Fail")
df["grade"]=df["Marks"].apply(lambda x: "A" if x>=80 else "B" if x>= 60 else "C")
df.to_csv("student_pandas.csv")
print("student_pandas.csv creadted")
print(df)



Shape: (8, 4)

Data types:
 Name     object
Age       int64
Marks     int64
City     object
dtype: object

Basic statistics:
              Age      Marks
count   8.000000   8.000000
mean   20.750000  83.500000
std     1.035098  10.836446
min    19.000000  65.000000
25%    20.000000  76.500000
50%    21.000000  87.000000
75%    21.250000  91.250000
max    22.000000  96.000000

INFO
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    8 non-null      object
 1   Age     8 non-null      int64 
 2   Marks   8 non-null      int64 
 3   City    8 non-null      object
dtypes: int64(2), object(2)
memory usage: 388.0+ bytes
student_pandas.csv creadted
      Name  Age  Marks        City Result grade
0   Naeven   20     85   Bengaluru   Pass     A
1    Akash   21     72      Mysore   Pass     B
2   Devika   19     91   Bengaluru   Pass     A
3   Shreya   22     65   

In [24]:
df=pd.read_csv("student_pandas.csv")

passed=df[df["Result"]=="Pass"]
print("Passed students:")
print(passed)

#Filtering students from Shivamogga
bengaluru=df[df["City"]=="Shivamogga"]
print("\nstudents from Shivamogga are:")
print(bengaluru)

#Grade A students
grade_a_students=df[df["grade"]=="A"]
print("\nstudents with Grade A are:")
print(grade_a_students)

sorted_marks=df.sort_values("Marks",ascending=False)
print("\nSorted the marks(high to low):")
print(sorted_marks)

#sort by Name Alphabetically
sorted_name=df.sort_values("Name",ascending=True)
print("\n Sorted names by alphabetically ")
print(sorted_name)

Passed students:
   Unnamed: 0     Name  Age  Marks        City Result grade
0           0   Naeven   20     85   Bengaluru   Pass     A
1           1    Akash   21     72      Mysore   Pass     B
2           2   Devika   19     91   Bengaluru   Pass     A
3           3   Shreya   22     65       Hubli   Pass     B
4           4   Nithin   20     78   Mangaluru   Pass     B
5           5  vidarth   21     89    Dharwada   Pass     A
6           6    vinay   21     92  Shivamogga   Pass     A
7           7   Nandan   22     96  Shivamogga   Pass     A

students from Shivamogga are:
   Unnamed: 0    Name  Age  Marks        City Result grade
6           6   vinay   21     92  Shivamogga   Pass     A
7           7  Nandan   22     96  Shivamogga   Pass     A

students with Grade A are:
   Unnamed: 0     Name  Age  Marks        City Result grade
0           0   Naeven   20     85   Bengaluru   Pass     A
2           2   Devika   19     91   Bengaluru   Pass     A
5           5  vidarth   21