In [1]:
# Part 0 – Data Creation

import pandas as pd
import numpy as np

data = {
    "Name": ["Navami", "Akash", "Devika", "Shreya", "Nithin",
             "Komal", "Bhuvan", "Kaveri", "Vathsala", "Disha",
             "Vasukeesha", "Akhil", "Rajeshwari", "Mandara", "Thrishanth"],
    "Age": [20, 21, 19, 22, 20, 21, 20, 19, 21, 20, 22, 21, 20, 19, 21],
    "City": ["Bengaluru", "Mysuru", "Bengaluru", "Hubli", "Bengaluru",
             "Mysuru", "Hubli", "Bengaluru", "Mysuru", "Bengaluru",
             "Hubli", "Bengaluru", "Mysuru", "Bengaluru", "Hubli"],
    "Marks": [85, 72, 91, 55, 78, 65, 48, 88, 70, 92,
              58, 83, 67, 45, 76],
    "Subject": ["Python", "Python", "Data Analysis", "Python", "Data Analysis",
                "Python", "Data Analysis", "Python", "Data Analysis", "Python",
                "Python", "Data Analysis", "Python", "Data Analysis", "Python"]
}

df = pd.DataFrame(data)
df

,Name,Age,City,Marks,Subject
0,Navami,20,Bengaluru,85,Python
1,Akash,21,Mysuru,72,Python
2,Devika,19,Bengaluru,91,Data Analysis
3,Shreya,22,Hubli,55,Python
4,Nithin,20,Bengaluru,78,Data Analysis
5,Komal,21,Mysuru,65,Python
6,Bhuvan,20,Hubli,48,Data Analysis
7,Kaveri,19,Bengaluru,88,Python
8,Vathsala,21,Mysuru,70,Data Analysis
9,Disha,20,Bengaluru,92,Python


In [4]:
# Part 1 – Data Loading and Validation

# Save to CSV
df.to_csv("students_capstone.csv", index=False)

# Load with error handling
try:
    df = pd.read_csv("students_capstone.csv")
    print("File loaded successfully")
except FileNotFoundError:
    print("File not found")

# Check missing values
print("\nMissing Values:")
print(df.isnull().sum())

# Basic info
print("\nShape:", df.shape)
print("\nColumns:", df.columns.tolist())
print("\nData Types:")
print(df.dtypes)


File loaded successfully

Missing Values:
Name       0
Age        0
City       0
Marks      0
Subject    0
dtype: int64

Shape: (15, 5)

Columns: ['Name', 'Age', 'City', 'Marks', 'Subject']

Data Types:
Name       object
Age         int64
City       object
Marks       int64
Subject    object
dtype: object


In [5]:
# Part 2 – Data Processing

# Result column
df["Result"] = np.where(df["Marks"] >= 60, "Pass", "Fail")

# Grade column
def assign_grade(marks):
    if marks >= 80:
        return "A"
    elif marks >= 60:
        return "B"
    else:
        return "C"

df["Grade"] = df["Marks"].apply(assign_grade)

# Passed students
print("\nPassed Students:")
print(df[df["Result"] == "Pass"])

# Grade A students
print("\nGrade A Students:")
print(df[df["Grade"] == "A"])

# Top 5 by marks
print("\nTop 5 Students:")
print(df.sort_values(by="Marks", ascending=False).head(5))



Passed Students:
          Name  Age       City  Marks        Subject Result Grade
0       Navami   20  Bengaluru     85         Python   Pass     A
1        Akash   21     Mysuru     72         Python   Pass     B
2       Devika   19  Bengaluru     91  Data Analysis   Pass     A
4       Nithin   20  Bengaluru     78  Data Analysis   Pass     B
5        Komal   21     Mysuru     65         Python   Pass     B
7       Kaveri   19  Bengaluru     88         Python   Pass     A
8     Vathsala   21     Mysuru     70  Data Analysis   Pass     B
9        Disha   20  Bengaluru     92         Python   Pass     A
11       Akhil   21  Bengaluru     83  Data Analysis   Pass     A
12  Rajeshwari   20     Mysuru     67         Python   Pass     B
14  Thrishanth   21      Hubli     76         Python   Pass     B

Grade A Students:
      Name  Age       City  Marks        Subject Result Grade
0   Navami   20  Bengaluru     85         Python   Pass     A
2   Devika   19  Bengaluru     91  Data Analysi

In [6]:
# Part 3 – NumPy Analysis

marks_array = df["Marks"].to_numpy()

print("Sum:", marks_array.sum())
print("Mean:", marks_array.mean())
print("Max:", marks_array.max())
print("Min:", marks_array.min())
print("Std Dev:", marks_array.std())

# Scores above average
print("\nAbove Average Scores:")
print(marks_array[marks_array > marks_array.mean()])

# Sorted descending
print("\nSorted Marks (Desc):")
print(np.sort(marks_array)[::-1])

# 2D array: Python vs Data Analysis
python_marks = df[df["Subject"] == "Python"]["Marks"].to_numpy()
da_marks = df[df["Subject"] == "Data Analysis"]["Marks"].to_numpy()

min_len = min(len(python_marks), len(da_marks))
marks_2d = np.vstack((python_marks[:min_len], da_marks[:min_len]))

print("\n2D Array:")
print(marks_2d)

print("\nRow Means:")
print(marks_2d.mean(axis=1))

Sum: 1073
Mean: 71.53333333333333
Max: 92
Min: 45
Std Dev: 14.659998484159386

Above Average Scores:
[85 72 91 78 88 92 83 76]

Sorted Marks (Desc):
[92 91 88 85 83 78 76 72 70 67 65 58 55 48 45]

2D Array:
[[85 72 55 65 88 92]
 [91 78 48 70 83 45]]

Row Means:
[76.16666667 69.16666667]


In [7]:
# Part 4 – Pandas Analysis

# City-wise aggregation
print("\nCity-wise Statistics:")
print(df.groupby("City")["Marks"].agg(["mean", "max", "min", "count"]))

# Grade-wise count
print("\nGrade-wise Count:")
print(df.groupby("Grade").size())

# Subject-wise average
print("\nSubject-wise Average Marks:")
print(df.groupby("Subject")["Marks"].mean())

# Describe
print("\nMarks Description:")
print(df["Marks"].describe())

# Top & bottom students
print("\nTop 3 Students:")
print(df.nlargest(3, "Marks")[["Name", "Marks"]])

print("\nBottom 3 Students:")
print(df.nsmallest(3, "Marks")[["Name", "Marks"]])

# Pass rate per city
pass_rate = df[df["Result"] == "Pass"].groupby("City").size() / df.groupby("City").size() * 100
print("\nPass Rate per City (%):")
print(pass_rate)


City-wise Statistics:
                mean  max  min  count
City                                 
Bengaluru  80.285714   92   45      7
Hubli      59.250000   76   48      4
Mysuru     68.500000   72   65      4

Grade-wise Count:
Grade
A    5
B    6
C    4
dtype: int64

Subject-wise Average Marks:
Subject
Data Analysis    69.166667
Python           73.111111
Name: Marks, dtype: float64

Marks Description:
count    15.000000
mean     71.533333
std      15.174540
min      45.000000
25%      61.500000
50%      72.000000
75%      84.000000
max      92.000000
Name: Marks, dtype: float64

Top 3 Students:
     Name  Marks
9   Disha     92
2  Devika     91
7  Kaveri     88

Bottom 3 Students:
       Name  Marks
13  Mandara     45
6    Bhuvan     48
3    Shreya     55

Pass Rate per City (%):
City
Bengaluru     85.714286
Hubli         25.000000
Mysuru       100.000000
dtype: float64


In [8]:
# Part 5 – Summary Report

total_students = len(df)
avg_marks = df["Marks"].mean()
max_marks = df["Marks"].max()
min_marks = df["Marks"].min()
median_marks = df["Marks"].median()
pass_count = (df["Result"] == "Pass").sum()
fail_count = (df["Result"] == "Fail").sum()
pass_rate = (pass_count / total_students) * 100

grade_summary = df["Grade"].value_counts()
city_avg = df.groupby("City")["Marks"].mean()

top_3 = df.nlargest(3, "Marks")
attention = df[df["Marks"] < 60]

print("""
PHASE 1 CAPSTONE - STUDENT ANALYSIS REPORT
==================================================
""")
print(f"Total Students     : {total_students}")
print(f"Average Marks      : {avg_marks:.2f}")
print(f"Highest Marks      : {max_marks}")
print(f"Lowest Marks       : {min_marks}")
print(f"Median Marks       : {median_marks}")
print(f"Pass Count         : {pass_count}")
print(f"Fail Count         : {fail_count}")
print(f"Pass Rate          : {pass_rate:.2f}%")

print("\n--------------------------------------------------")
print("GRADE SUMMARY")
for grade, count in grade_summary.items():
    print(f"Grade {grade}          : {count} students")

print("\n--------------------------------------------------")
print("CITY-WISE AVERAGE MARKS")
for city, avg in city_avg.items():
    print(f"{city:<16}: {avg:.2f}")

print("\n--------------------------------------------------")
print("TOP 3 STUDENTS")
for i, row in top_3.iterrows():
    print(f"{row['Name']} - {row['Marks']}")

print("\n--------------------------------------------------")
print("STUDENTS NEEDING ATTENTION (Marks < 60)")
for i, row in attention.iterrows():
    print(f"{row['Name']} - {row['Marks']}")

print("==================================================")

# Save summary CSV
summary_df = df[["Name", "Marks", "Grade", "Result", "City"]]
summary_df.to_csv("capstone_summary_report.csv", index=False)


PHASE 1 CAPSTONE - STUDENT ANALYSIS REPORT

Total Students     : 15
Average Marks      : 71.53
Highest Marks      : 92
Lowest Marks       : 45
Median Marks       : 72.0
Pass Count         : 11
Fail Count         : 4
Pass Rate          : 73.33%

--------------------------------------------------
GRADE SUMMARY
Grade B          : 6 students
Grade A          : 5 students
Grade C          : 4 students

--------------------------------------------------
CITY-WISE AVERAGE MARKS
Bengaluru       : 80.29
Hubli           : 59.25
Mysuru          : 68.50

--------------------------------------------------
TOP 3 STUDENTS
Disha - 92
Devika - 91
Kaveri - 88

--------------------------------------------------
STUDENTS NEEDING ATTENTION (Marks < 60)
Shreya - 55
Bhuvan - 48
Vasukeesha - 58
Mandara - 45
